### PR TITLE
Add Link Editing

### PR DESCRIPTION
**Pull request by TGS963**

### CODE REVIEW

**Comment by NayamAmarshe** [comment]
The title apprarently is empty when you add the link directly.
image

**Comment by TGS963** [comment]
Yes, the title is a custom float that occurs when you hover over the link. It's empty by default

**Comment by NayamAmarshe** [comment]
I think we need to implement it how bangle.dev does.

**Comment by TGS963** [comment]
I can't edit or create any link on their site. What's up with that

**Pull request merged**
