### PR TITLE
Add dark theme support through `next-themes`

### PR DESCRIPTION
**Pull request by datsfilipe**
This adds dark theme support using the [next-themes](https://github.com/pacocoursey/next-themes) package.

### The benefits of using `next-themes` here are:
- Simple to use and integrate with Next.js and TailwindCSS.
- All other benefits they [mention](https://github.com/pacocoursey/next-themes#next-themes--) on their github page.

### Features included in this pull request:
- `next-themes` configured.
- `ThemeChanger` component to switch from light to dark mode (I included it in the `Sidebar` in the dashboard page, where I thought it would be a good place).
- To add dark colors to the background, text and more, just use the `dark:` prefix, as explained in the TailwindCSS documentation.

#### **Notes:**
- Since I don't know exactly which colors will be used in dark mode, I'll leave it to the project maintainers to decide.
- The same for the content of the `ThemeChanger` component, which for now is just informing which theme will be applied next when clicked.

#### Theme change demo (I just added the bg color for testing):

Gif showing theme change

Related to the #63 issue created by me.

### CODE REVIEW

**Comment by NayamAmarshe** [comment]
Thanks a lot for the PR!
This is certainly very useful, however, our plans for dark mode are for a later sprint.

I really want to merge it but then we'll have a half-working dark mode, which won't be too good.

I'll have to think what I should do with this PR 😅

**Comment by datsfilipe** [comment]
Oh, I get it. No problem at all for me since I did it for fun.

**Comment by NayamAmarshe** [comment]
> Oh, I get it. No problem at all for me since I did it for fun.

I'll try my best to not let your efforts go to waste :)

**Comment by NayamAmarshe** [comment]
Forked here: https://github.com/NayamAmarshe/writedown/pull/68

v2.5 will have Dark Mode :)

**Pull request closed without merging**
